version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/authorisation"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-enrichment"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-minimisation"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-validation"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lib"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/platform"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/platform"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/prometheus"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/grafana"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: bundler
    directory: "/techdocs"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: npm
    directory: /terraform/modules/gro_ingestion_service/lambdas
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/backend"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/backend-prod"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/demo"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/dev"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/prod"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/shared"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/assume_admin_role_alert"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/assume_admin_role_alert_all_regions"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/backup_vault"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/bootstrap"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/cloudtrail"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/cloudtrail_cloudwatch_alarm"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/cloudwatch_alarm_dashboard"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/cloudwatch_metrics_dashboard"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/cognito"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/data_share_service"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/deploy_hook"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/dwp_dev"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/ecr"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/github_iam"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/grafana"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/gro_ingestion_service"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/iam_user_role"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/iam_user_roles"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/len"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/lev_api"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/policies"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/route53"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/s3"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/simple_user_pool_client"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/sns"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/sqs"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/statuscake"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform/modules/vpc"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
