name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image:
        required: true
        type: string
      registry:
        required: true
        type: string

jobs:
  trigger-codedeploy:
    name: Trigger Codedeploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Setup variables for environment
        id: vars
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "base_directory=.aws" >> $GITHUB_OUTPUT
          echo "ecs_task_definition_filepath=.aws/task-definition.json" >> $GITHUB_OUTPUT
          echo "codedeploy_appspec_filepath=.aws/appspec.json" >> $GITHUB_OUTPUT
          echo "codedeploy_appspec_template_filepath=ci/appspec-template.json" >> $GITHUB_OUTPUT

          echo "ecs_task_definition=$ENVIRONMENT-gdx-data-share-poc" >> $GITHUB_OUTPUT
          echo "ecs_container_name=$ENVIRONMENT-gdx-data-share-poc" >> $GITHUB_OUTPUT
          echo "ecs_service=$ENVIRONMENT-gdx-data-share-poc" >> $GITHUB_OUTPUT
          echo "ecs_cluster=$ENVIRONMENT" >> $GITHUB_OUTPUT

          echo "container_port=8080" >> $GITHUB_OUTPUT

          echo "codedeploy_application=$ENVIRONMENT-gdx-data-share-poc" >> $GITHUB_OUTPUT
          echo "codedeploy_deployment_group=$ENVIRONMENT-gdx-data-share-poc" >> $GITHUB_OUTPUT

          echo "prometheus_container_name=adot-collector" >> $GITHUB_OUTPUT
          echo "prometheus_image_name=prometheus-adot" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::776473272850:role/${{ inputs.environment }}-github-oidc-deploy
          role-session-name: codedeploy
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Get current datetime as output
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%dT%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Add tag for ${{ inputs.environment }} environment
        uses: abronin/ecr-retag-action@v1
        with:
          repository: gdx-data-share-poc
          tag: ${{ github.sha }}
          new-tags: ${{ inputs.environment }}-${{ steps.datetime.outputs.datetime }}

      - name: Get the most recent prometheus image ID
        id: prometheus-adot-image
        run: |
          IMAGE_TAG=$(aws ecr describe-images --repository-name ${{ steps.vars.outputs.prometheus_image_name }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' | jq --raw-output)
          echo "image=${{ inputs.registry }}/${{ steps.vars.outputs.prometheus_image_name }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set ECS task definition
        id: task-definition
        env:
          ECS_TASK_DEFINITION: ${{ steps.vars.outputs.ecs_task_definition }}
          ECS_TASK_DEFINITION_DIRECTORY: ${{ steps.vars.outputs.base_directory }}
          ECS_TASK_DEFINITION_FILEPATH: ${{ steps.vars.outputs.ecs_task_definition_filepath }}
        run: |
          mkdir -p $ECS_TASK_DEFINITION_DIRECTORY
          aws ecs describe-task-definition --task-definition "$ECS_TASK_DEFINITION" | jq '.taskDefinition' > $ECS_TASK_DEFINITION_FILEPATH

      - name: Fill in the prometheus image ID in the Amazon ECS task definition
        id: update-task-def-for-prometheus
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.vars.outputs.ecs_task_definition_filepath }}
          container-name: ${{ steps.vars.outputs.prometheus_container_name }}
          image: ${{ steps.prometheus-adot-image.outputs.image }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.update-task-def-for-prometheus.outputs.task-definition }}
          container-name: ${{ steps.vars.outputs.ecs_container_name }}
          image: ${{ inputs.image }}

      - name: Set appspec.json values
        id: appspec
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          CONTAINER_PORT: ${{ steps.vars.outputs.container_port }}
          ECS_TASK_DEFINITION: ${{ steps.vars.outputs.ecs_task_definition }}
          CODEDEPLOY_APPSPEC_FILEPATH: ${{ steps.vars.outputs.codedeploy_appspec_filepath }}
          CODEDEPLOY_APPSPEC_TEMPLATE_FILEPATH: ${{ steps.vars.outputs.codedeploy_appspec_template_filepath }}
        run: |
          ECS_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition="$ECS_TASK_DEFINITION" | jq '.taskDefinition.taskDefinitionArn')
          HOOK_LAMBDA_ARN=$(aws lambda get-function --function-name="$ENVIRONMENT-codedeploy-before-traffic-hook" | jq .Configuration.FunctionArn)
          cat $CODEDEPLOY_APPSPEC_TEMPLATE_FILEPATH \
          | jq --arg key "$ECS_TASK_DEFINITION_ARN" '.Resources[].TargetService.Properties.TaskDefinition=$key' \
          | jq --arg key "$CONTAINER_PORT" '.Resources[].TargetService.Properties.LoadBalancerInfo.ContainerPort=$key' \
          | jq --arg key "$ECS_TASK_DEFINITION" '.Resources[].TargetService.Properties.LoadBalancerInfo.ContainerName=$key' \
          | jq --arg key "$HOOK_LAMBDA_ARN" '.Hooks[].AfterAllowTestTraffic=$key' \
          > $CODEDEPLOY_APPSPEC_FILEPATH
          sed -i 's#\\"##g' $CODEDEPLOY_APPSPEC_FILEPATH

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          service: ${{ steps.vars.outputs.ecs_service }}
          cluster: ${{ steps.vars.outputs.ecs_cluster }}
          wait-for-service-stability: true
          codedeploy-appspec: ${{ steps.vars.outputs.codedeploy_appspec_filepath }}
          codedeploy-application: ${{ steps.vars.outputs.codedeploy_application }}
          codedeploy-deployment-group: ${{ steps.vars.outputs.codedeploy_deployment_group }}
