name: Infrastructure - Pull request

on:
  pull_request:
    paths-ignore:
      - "terraform/**"
      - ".github/workflows/**"
  merge_group:
    paths-ignore:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: 'echo "No build required"'

  validate-terraform:
    strategy:
      matrix:
        env: [dev, demo, shared, prod]
      fail-fast: false
    name: Validate ${{ matrix.env }} Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: 'echo "No build required"'
