name: Infrastructure - Pull request

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  merge_group:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive

  validate-terraform:
    strategy:
      matrix:
        include:
          - env: dev
            account_number: 776473272850
          - env: demo
            account_number: 776473272850
          - env: shared
            account_number: 776473272850
          - env: prod
            account_number: 255773200490
      fail-fast: false
    name: Validate ${{ matrix.env }} Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: terraform/${{ matrix.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_number }}:role/github-oidc-pull-request
          role-session-name: validate-terraform
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        id: init
        run: terraform init -input=false -lock=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -lock=false

