name: Infrastructure - Main

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  deploy-terraform:
    strategy:
      matrix:
        include:
          - env: dev
            account_number: 776473272850
          - env: demo
            account_number: 776473272850
          - env: shared
            account_number: 776473272850
          - env: prod
            account_number: 255773200490
      fail-fast: false
    name: Deploy ${{ matrix.env }} Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ matrix.env }}
    defaults:
      run:
        working-directory: terraform/${{ matrix.env }}
    concurrency:
      group: infrastructure-pipeline-${{ matrix.env }}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_number }}:role/${{ matrix.env }}-github-oidc-deploy
          role-session-name: deploy-terraform
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        # Terraform's "detailed-exitcode" codes are: 0 for "no changes", 1 for errors, 2 for "valid changes"
        # Output a plan even though we don't use it here - we need the printed output to be the same as in the apply job below
        # We don't save the plan as an artefact as it's sensitive and this repo is public
        run: terraform plan -no-color -input=false -detailed-exitcode -out=plan.tfplan
        continue-on-error: true

      - name: Fail job if plan failed
        run: if [ ${{ steps.plan.outputs.exitcode }} -eq 1 ]; then exit 1; else exit 0; fi

      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == 2
        run: terraform apply -auto-approve -input=false plan.tfplan
