name: Update Prometheus

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "prometheus/**"

jobs:
  build-prometheus-image:
    name: Build Docker image and push to ECR
    environment: shared
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: ./prometheus
          push: false
          tags: ${{ github.ref_name }}:latest
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ${{ github.ref_name }}:latest
          exit-code: 1
          trivyignores: prometheus/.trivyignore

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::776473272850:role/shared-github-oidc-deploy
          role-session-name: push-prometheus-image
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push base image to Amazon ECR
        id: push-image
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/prometheus-adot
        run: |
          docker tag ${{ github.ref_name }}:latest $IMAGE:${{ github.sha }}
          docker push $IMAGE:${{ github.sha }}
